// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenSound.Banco;

#nullable disable

namespace ScreenSound.Shared.Dados.Migrations
{
    [DbContext(typeof(ScreenSoundContext))]
    partial class ScreenSoundContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeneroMusica", b =>
                {
                    b.Property<int>("GenerosId")
                        .HasColumnType("int");

                    b.Property<int>("MusicasId")
                        .HasColumnType("int");

                    b.HasKey("GenerosId", "MusicasId");

                    b.HasIndex("MusicasId");

                    b.ToTable("GeneroMusica");

                    b.HasData(
                        new
                        {
                            GenerosId = 2,
                            MusicasId = 1
                        },
                        new
                        {
                            GenerosId = 2,
                            MusicasId = 2
                        },
                        new
                        {
                            GenerosId = 1,
                            MusicasId = 3
                        },
                        new
                        {
                            GenerosId = 1,
                            MusicasId = 4
                        },
                        new
                        {
                            GenerosId = 1,
                            MusicasId = 5
                        },
                        new
                        {
                            GenerosId = 3,
                            MusicasId = 5
                        });
                });

            modelBuilder.Entity("ScreenSound.Modelos.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Um dos maiores cantores e compositores da MPB...",
                            FotoPerfil = "url-da-foto-djavan",
                            Nome = "Djavan"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Banda de rock irlandesa formada em 1976...",
                            FotoPerfil = "url-da-foto-u2",
                            Nome = "U2"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Banda de rock britânica formada em Londres em 1970...",
                            FotoPerfil = "url-da-foto-queen",
                            Nome = "Queen"
                        });
                });

            modelBuilder.Entity("ScreenSound.Modelos.Musica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnoLancamento")
                        .HasColumnType("int");

                    b.Property<int?>("ArtistaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.ToTable("Musicas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoLancamento = 1982,
                            ArtistaId = 1,
                            Nome = "Sina"
                        },
                        new
                        {
                            Id = 2,
                            AnoLancamento = 1989,
                            ArtistaId = 1,
                            Nome = "Oceano"
                        },
                        new
                        {
                            Id = 3,
                            AnoLancamento = 1987,
                            ArtistaId = 2,
                            Nome = "With or Without You"
                        },
                        new
                        {
                            Id = 4,
                            AnoLancamento = 1991,
                            ArtistaId = 2,
                            Nome = "One"
                        },
                        new
                        {
                            Id = 5,
                            AnoLancamento = 1975,
                            ArtistaId = 3,
                            Nome = "Bohemian Rhapsody"
                        });
                });

            modelBuilder.Entity("ScreenSound.Shared.Modelos.Modelos.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Gênero de música popular que se desenvolveu durante e após a década de 1950.",
                            Nome = "Rock"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Música popular brasileira, um estilo musical que surgiu no Brasil.",
                            Nome = "MPB"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Música popular, geralmente orientada para o mercado comercial.",
                            Nome = "Pop"
                        });
                });

            modelBuilder.Entity("GeneroMusica", b =>
                {
                    b.HasOne("ScreenSound.Shared.Modelos.Modelos.Genero", null)
                        .WithMany()
                        .HasForeignKey("GenerosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScreenSound.Modelos.Musica", null)
                        .WithMany()
                        .HasForeignKey("MusicasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScreenSound.Modelos.Musica", b =>
                {
                    b.HasOne("ScreenSound.Modelos.Artista", "Artista")
                        .WithMany("Musicas")
                        .HasForeignKey("ArtistaId");

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("ScreenSound.Modelos.Artista", b =>
                {
                    b.Navigation("Musicas");
                });
#pragma warning restore 612, 618
        }
    }
}
